# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\CodeField\CODE_PY\ToolsCollection\app\applications\SecretFile\ui_single_task_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SingleTaskWidget(object):
    def setupUi(self, SingleTaskWidget):
        SingleTaskWidget.setObjectName("SingleTaskWidget")
        SingleTaskWidget.resize(493, 77)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        SingleTaskWidget.setFont(font)
        SingleTaskWidget.setWindowTitle("Form")
        self.horizontalLayout = QtWidgets.QHBoxLayout(SingleTaskWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_src = CaptionLabel(SingleTaskWidget)
        self.label_src.setText("Caption label")
        self.label_src.setObjectName("label_src")
        self.verticalLayout.addWidget(self.label_src)
        self.progressBar = ProgressBar(SingleTaskWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(SingleTaskWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.label_state = StrongBodyLabel(SingleTaskWidget)
        self.label_state.setText("Strong body label")
        self.label_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state.setObjectName("label_state")
        self.horizontalLayout.addWidget(self.label_state)
        self.line_3 = QtWidgets.QFrame(SingleTaskWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.pushButton = ToolButton(SingleTaskWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = ToolButton(SingleTaskWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(4, 1)
        self.horizontalLayout.setStretch(5, 1)

        self.retranslateUi(SingleTaskWidget)
        self.pushButton.clicked.connect(SingleTaskWidget.pause_toggled) # type: ignore
        self.pushButton_2.clicked.connect(SingleTaskWidget.remove) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SingleTaskWidget)

    def retranslateUi(self, SingleTaskWidget):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton.setToolTip(_translate("SingleTaskWidget", "pause"))
        self.pushButton_2.setToolTip(_translate("SingleTaskWidget", "remove"))
from qfluentwidgets import CaptionLabel, ProgressBar, StrongBodyLabel, ToolButton
