# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\CodeField\CODE_PY\ToolsCollection\app\applications\SecretFile\ui_secret_file_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecretFileInterface(object):
    def setupUi(self, SecretFileInterface):
        SecretFileInterface.setObjectName("SecretFileInterface")
        SecretFileInterface.resize(415, 460)
        SecretFileInterface.setAcceptDrops(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SecretFileInterface)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(SecretFileInterface)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.CaptionLabel = CaptionLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CaptionLabel.sizePolicy().hasHeightForWidth())
        self.CaptionLabel.setSizePolicy(sizePolicy)
        self.CaptionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.gridLayout.addWidget(self.CaptionLabel, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_file = PlainTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_file.sizePolicy().hasHeightForWidth())
        self.edit_file.setSizePolicy(sizePolicy)
        self.edit_file.setMinimumSize(QtCore.QSize(0, 48))
        self.edit_file.setMaximumSize(QtCore.QSize(16777215, 48))
        self.edit_file.setReadOnly(True)
        self.edit_file.setObjectName("edit_file")
        self.horizontalLayout.addWidget(self.edit_file)
        self.button_open_file = ToolButton(self.widget)
        self.button_open_file.setIconSize(QtCore.QSize(32, 32))
        self.button_open_file.setObjectName("button_open_file")
        self.horizontalLayout.addWidget(self.button_open_file)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.CaptionLabel_2 = CaptionLabel(self.widget)
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.gridLayout.addWidget(self.CaptionLabel_2, 1, 0, 1, 1)
        self.edit_password = PasswordLineEdit(self.widget)
        self.edit_password.setMinimumSize(QtCore.QSize(0, 48))
        self.edit_password.setMaximumSize(QtCore.QSize(16777215, 48))
        self.edit_password.setObjectName("edit_password")
        self.gridLayout.addWidget(self.edit_password, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.button_encode = PushButton(self.widget)
        self.button_encode.setObjectName("button_encode")
        self.horizontalLayout_3.addWidget(self.button_encode)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.button_decode = PushButton(self.widget)
        self.button_decode.setObjectName("button_decode")
        self.horizontalLayout_3.addWidget(self.button_decode)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.widget)
        self.line = QtWidgets.QFrame(SecretFileInterface)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.list_widget = ListWidget(SecretFileInterface)
        self.list_widget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.list_widget.setObjectName("list_widget")
        self.verticalLayout_2.addWidget(self.list_widget)

        self.retranslateUi(SecretFileInterface)
        self.button_encode.clicked.connect(SecretFileInterface.encode) # type: ignore
        self.button_decode.clicked.connect(SecretFileInterface.decode) # type: ignore
        self.button_open_file.clicked.connect(SecretFileInterface.open_file) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SecretFileInterface)

    def retranslateUi(self, SecretFileInterface):
        _translate = QtCore.QCoreApplication.translate
        SecretFileInterface.setWindowTitle(_translate("SecretFileInterface", "Secret File"))
        self.CaptionLabel.setText(_translate("SecretFileInterface", "File:"))
        self.button_open_file.setToolTip(_translate("SecretFileInterface", "open file"))
        self.CaptionLabel_2.setText(_translate("SecretFileInterface", "Password:"))
        self.button_encode.setText(_translate("SecretFileInterface", "Encode"))
        self.button_decode.setText(_translate("SecretFileInterface", "Decode"))
from qfluentwidgets import CaptionLabel, ListWidget, PasswordLineEdit, PlainTextEdit, PushButton, ToolButton
