# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\CodeField\CODE_PY\ToolsCollection\app\applications\demo\ui_demo_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DemoInterface(object):
    def setupUi(self, DemoInterface):
        DemoInterface.setObjectName("DemoInterface")
        DemoInterface.resize(240, 320)

        self.retranslateUi(DemoInterface)
        QtCore.QMetaObject.connectSlotsByName(DemoInterface)

    def retranslateUi(self, DemoInterface):
        _translate = QtCore.QCoreApplication.translate
        DemoInterface.setWindowTitle(_translate("DemoInterface", "Demo"))
