# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\JiyuHe\Documents\CodeField\CODE_PY\ToolsCollection\app\applications\Hashlib\ui_hashlib_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HashlibInterface(object):
    def setupUi(self, HashlibInterface):
        HashlibInterface.setObjectName("HashlibInterface")
        HashlibInterface.resize(940, 604)
        HashlibInterface.setAcceptDrops(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(HashlibInterface)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_bar = TabBar(HashlibInterface)
        self.tab_bar.setMovable(True)
        self.tab_bar.setScrollable(False)
        self.tab_bar.setObjectName("tab_bar")
        self.verticalLayout.addWidget(self.tab_bar)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(HashlibInterface)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CaptionLabel = CaptionLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CaptionLabel.sizePolicy().hasHeightForWidth())
        self.CaptionLabel.setSizePolicy(sizePolicy)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.horizontalLayout.addWidget(self.CaptionLabel)
        self.combobox_type = ComboBox(self.widget)
        self.combobox_type.setMinimumSize(QtCore.QSize(0, 48))
        self.combobox_type.setObjectName("combobox_type")
        self.horizontalLayout.addWidget(self.combobox_type)
        self.button_hash = ToolButton(self.widget)
        self.button_hash.setIconSize(QtCore.QSize(32, 32))
        self.button_hash.setObjectName("button_hash")
        self.horizontalLayout.addWidget(self.button_hash)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.widget_input = InputWidget(self.widget)
        self.widget_input.setObjectName("widget_input")
        self.verticalLayout_2.addWidget(self.widget_input)
        self.CaptionLabel_2 = CaptionLabel(self.widget)
        self.CaptionLabel_2.setText("md5:")
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.verticalLayout_2.addWidget(self.CaptionLabel_2)
        self.edit_md5 = LineEdit(self.widget)
        self.edit_md5.setReadOnly(True)
        self.edit_md5.setObjectName("edit_md5")
        self.verticalLayout_2.addWidget(self.edit_md5)
        self.CaptionLabel_3 = CaptionLabel(self.widget)
        self.CaptionLabel_3.setText("sha1:")
        self.CaptionLabel_3.setObjectName("CaptionLabel_3")
        self.verticalLayout_2.addWidget(self.CaptionLabel_3)
        self.edit_sha1 = LineEdit(self.widget)
        self.edit_sha1.setReadOnly(True)
        self.edit_sha1.setObjectName("edit_sha1")
        self.verticalLayout_2.addWidget(self.edit_sha1)
        self.CaptionLabel_4 = CaptionLabel(self.widget)
        self.CaptionLabel_4.setText("sha256:")
        self.CaptionLabel_4.setObjectName("CaptionLabel_4")
        self.verticalLayout_2.addWidget(self.CaptionLabel_4)
        self.edit_sha256 = LineEdit(self.widget)
        self.edit_sha256.setReadOnly(True)
        self.edit_sha256.setObjectName("edit_sha256")
        self.verticalLayout_2.addWidget(self.edit_sha256)
        self.CaptionLabel_5 = CaptionLabel(self.widget)
        self.CaptionLabel_5.setText("sha512:")
        self.CaptionLabel_5.setObjectName("CaptionLabel_5")
        self.verticalLayout_2.addWidget(self.CaptionLabel_5)
        self.edit_sha512 = TextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_sha512.sizePolicy().hasHeightForWidth())
        self.edit_sha512.setSizePolicy(sizePolicy)
        self.edit_sha512.setMinimumSize(QtCore.QSize(0, 66))
        self.edit_sha512.setMaximumSize(QtCore.QSize(16777215, 66))
        self.edit_sha512.setReadOnly(True)
        self.edit_sha512.setObjectName("edit_sha512")
        self.verticalLayout_2.addWidget(self.edit_sha512)
        self.horizontalLayout_2.addWidget(self.widget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(HashlibInterface)
        self.tab_bar.tabAddRequested.connect(HashlibInterface.add_new_tab) # type: ignore
        self.tab_bar.tabCloseRequested['int'].connect(HashlibInterface.remove_tab) # type: ignore
        self.tab_bar.currentChanged['int'].connect(HashlibInterface.set_current_tab) # type: ignore
        self.button_hash.clicked.connect(HashlibInterface.get_hash) # type: ignore
        self.combobox_type.currentIndexChanged['int'].connect(self.widget_input.setCurrentIndex) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(HashlibInterface)

    def retranslateUi(self, HashlibInterface):
        _translate = QtCore.QCoreApplication.translate
        HashlibInterface.setWindowTitle(_translate("HashlibInterface", "Hashlib"))
        self.CaptionLabel.setText(_translate("HashlibInterface", "Type:"))
        self.button_hash.setToolTip(_translate("HashlibInterface", "Get hash"))
from input_widget import InputWidget
from qfluentwidgets import CaptionLabel, ComboBox, LineEdit, TabBar, TextEdit, ToolButton
