# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\JiyuHe\Documents\CodeField\CODE_PY\ToolsCollection\app\applications\Hashlib\ui_input_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputWidget(object):
    def setupUi(self, InputWidget):
        InputWidget.setObjectName("InputWidget")
        InputWidget.resize(645, 320)
        InputWidget.setAcceptDrops(True)
        InputWidget.setWindowTitle("")
        InputWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_text = TextEdit(self.page)
        self.edit_text.setAcceptDrops(False)
        self.edit_text.setFrameShadow(QtWidgets.QFrame.Raised)
        self.edit_text.setObjectName("edit_text")
        self.horizontalLayout.addWidget(self.edit_text)
        InputWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 105, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.button_filepath = TransparentToolButton(self.page_2)
        self.button_filepath.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_filepath.sizePolicy().hasHeightForWidth())
        self.button_filepath.setSizePolicy(sizePolicy)
        self.button_filepath.setMinimumSize(QtCore.QSize(100, 100))
        self.button_filepath.setIconSize(QtCore.QSize(100, 100))
        self.button_filepath.setObjectName("button_filepath")
        self.horizontalLayout_2.addWidget(self.button_filepath)
        self.label_filepath = CaptionLabel(self.page_2)
        self.label_filepath.setWordWrap(True)
        self.label_filepath.setObjectName("label_filepath")
        self.horizontalLayout_2.addWidget(self.label_filepath)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 105, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        InputWidget.addWidget(self.page_2)

        self.retranslateUi(InputWidget)
        InputWidget.setCurrentIndex(0)
        self.button_filepath.clicked.connect(InputWidget.open_file) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(InputWidget)

    def retranslateUi(self, InputWidget):
        _translate = QtCore.QCoreApplication.translate
        self.edit_text.setPlaceholderText(_translate("InputWidget", "Enter the text here"))
        self.label_filepath.setText(_translate("InputWidget", "Drop the file here"))
from qfluentwidgets import CaptionLabel, TextEdit, TransparentToolButton
